[package]
name = "timv"
version = "0.1.0"
description = "Terminal image viewer"
authors = ["Ismaïl Senhaji <ismail.senhaji@gmail.com>"]
edition = "2018"

[dependencies]
clap = {version = "2.33", default-features = false}
image = "0.21"
itertools = "0.8"
termion = "1.5"
